### PR TITLE
Swap English text to symbolic emojis

### PR DESCRIPTION
**Pull request by n-hebert**
Contributes to the vision of #52

image

WDYT @toddmedema ?

The gutter may need its margins/buffers reworked to fit these, but I really like the immediate understanding of the emojis.

### CODE REVIEW

**Comment by toddmedema** [comment]
I like this direction! Two thoughts:
1. Are you able to increase the font size? The icons seem a bit small
2. The icons themselves are a bit indistinct (what is a sunset but a sunrise in reverse?) - I think a good way of clarifying this would be to add a ☀️ in the middle, at noon. Think you're up for that challenge? Looks like noon is always symmetrically between rise and set, so rather than having to calculate the full astronomical noon time, you could take a shortcut and just do sunrise + (sunset - sunrise) / 2

**Comment by toddmedema** [comment]
@n-hebert oddly, I just pulled this down and it's rendering fine for me - 
Screenshot 2024-04-26 at 5 09 54 PM

Maybe try pushing your latest changes and I can test again, and maybe we both test in a couple browsers to see if it's a browser-specific issue?

**Comment by n-hebert** [comment]
Ah! It's a firefox bug!
Chromium doesn't have it

**Comment by toddmedema** [comment]
Glad we found that out! Since only 3% of people use firefox and it's only a cosmetic issue, I think this is good enough for this project. Thank you for the contribution! What's next? 😁

**Pull request merged**
