### PR TITLE
Re-add dynamic version

### LINKED ISSUE #81: Have settings page version pull from package.json
This used to be done with a webpack build script, but that got ripped out in https://github.com/toddmedema/electrify/pull/77

Hopefully there's a way to do it within the create-react-app framework, I'd like to avoid having to eject and manage everything ourselves

### PR DESCRIPTION
**Pull request by n-hebert**
Closes #81

### CODE REVIEW

**Comment by toddmedema** [comment]
@n-hebert just tried it on my end and the version is coming up blank — I think maybe you put that value into your env by hand?

I did some googling and it seems like we also need to update the package.json commands to inject the version into the environment, this worked for me:

```
    "start": "REACT_APP_VERSION=$npm_package_version react-scripts start",
    "build": "REACT_APP_VERSION=$npm_package_version react-scripts build",
```

**Comment by n-hebert** [comment]
> @n-hebert just tried it on my end and the version is coming up blank — I think maybe you put that value into your env by hand?
> 
> I did some googling and it seems like we also need to update the package.json commands to inject the version into the environment, this worked for me:
> 
> ```
>     "start": "REACT_APP_VERSION=$npm_package_version react-scripts start",
>     "build": "REACT_APP_VERSION=$npm_package_version react-scripts build",
> ```

Ah woops! On it!

**Comment by n-hebert** [comment]
Hmm, were you on the latest version? I can confirm there was not an accidental manual insertion, and it wouldn't need the injection as you show since the `.env` file gets picked up automatically.

At least on my side, there's no REACT_APP_ anything in my shell env and it picks up from the `.env` file. Might need to pair if you can't fetch and find the same!

**Comment by toddmedema** [comment]
Oooh, I missed the .env change. Hmm, I'm hoping to have this pull from package.json so the version is only in one place / easier to maintain

**Comment by n-hebert** [comment]
> Oooh, I missed the .env change. Hmm, I'm hoping to have this pull from package.json so the version is only in one place / easier to maintain

I agree a hundred percent. I see it as a next ticket to do; merge this one, and then open an issue to de-duplicate.
Do you know if there's a low-hanging fruit for this one? I think that they are such diverse interests that it's not possible to have one read from the other right now.
Leveraging a build script to .env.local could be a bit flaky, but work, if the duplication isn't worth merging.

**Comment by n-hebert** [comment]
How about this commit, @toddmedema ? :smile:

**Review by toddmedema — APPROVED** [review]
Supposedly it's not ideal to including your package.json file like this for security reasons, but since this is an open source repo, the file is already public, so not applicable

**Pull request merged**
